### ISSUE TITLE
Provide detailed explanations to run the plugin in a development environment

### ISSUE THREAD

**Issue by erikyo** [wp-blocks/cf7-antispam#65]
We need to provide detailed explanations to run the plugin in a development environment for a better contribution experience. 

Maybe the best place is the readme.md in the ["Contributing"](https://github.com/erikyo/cf7-antispam#contributing-to-contact-form-7---antispam) section

>I really would like to help, but the composer CLI command doesn't run correctly and there is no working plugin after running the commands. And without any experience with Docker I have no idea how `wp-env start` should run anything. After installing docker it still says `command not found` (maybe just needs more configuration or a docker image I couldn't find yet).
If you can help me to get a running version from the Github main code, I will happily provide the PR.

_Originally posted by @Zodiac1978 in https://github.com/erikyo/cf7-antispam/issues/63#issuecomment-1823539885_

**Comment by gardenboi** [comment]
Hey @erikyo  should I write a full how-to on how to use the cli and wp-env correctly ? 
@johnhooks has included some links for the resources necessary to run node, composer, wp-env/docker, should we extend the documentation with a `how-to` so we might re-use it in future projects ?

**Comment by johnhooks** [comment]
A quick fix the the issue @erikyo quoted is to use the `wp-env` command through `npx` which should use the command installed in the `node_modules` directory.

```
npx wp-env start
```

**Comment by erikyo** [comment]
> should I write a full how-to on how to use the cli and wp-env correctly, (...) should we extend the documentation with a how-to so we might re-use it in future projects ?

@gardenboi, no worries for now! It's not really necessary at the moment. 

If it's something unrelated to the plugin itself, the right place might be on a potential plugin website or blog (if we ever get one) and keeping it here could get a bit overwhelming. However good idea, it wouldn't hurt to have it, I'm not ruling out the possibility of maybe opening a website / Git wiki section in the future, but I'd like to avoid it if we don't really need it at the moment.
