### ISSUE TITLE
"Anti-bot checks" gives me lots of false positives

### ISSUE THREAD

**Issue by Yerrun** [wp-blocks/cf7-antispam#91]
I checked all settings, but this is the one causing not spam to become marked as spam.

The server and many people who send emails are from Indonesia. I don't know if that is causing the problems. It looks like those emails are treated like bots. Many of the spam were marked as: 
- blacklisted score: 4; b8: 0.98
- blacklisted score: 7; b8: 0.99

When I investigated why more than 90% of the emails ended up as spam, I disabled all Settings. Then, I enabled them one-by-one and the only setting that marked legitimate emails as spam was "Enable anti-bot checks". 

I disabled this setting, and the plugin marks spam as spam and not spam as not spam.

**Comment by erikyo** [comment]
Do you have flamingo installed? can you please give a look at the reason why? you can find the reason in the Flamingo inbound message > spam > click on a mail -> check the metabox at the top right. should provide a better info about
![image](https://github.com/wp-blocks/cf7-antispam/assets/8550908/dadf4470-8a46-40f8-b915-49d32e24cf8a)

**Comment by Yerrun** [comment]
I just got this one, Erik.

Spam log: data_mismatch: Version mismatch '' != '0.6.0'; bot_fingerprint_extras: activity 0, mouseclick_activity, mousemove_activity, webgl, webgl_render; dsnbl: dnsbl-3.uceprotect.net, dnsbl.sorbs.net, zen.spamhaus.org, b.barracudacentral.org, all.spamrats.com

**Comment by Yerrun** [comment]
And other one

Spam log: data_mismatch: Version mismatch '' != '0.6.0'; bot_fingerprint_extras: activity 0, mouseclick_activity, mousemove_activity, webgl, webgl_render; dsnbl: dnsbl-2.uceprotect.net, dnsbl-3.uceprotect.net, zen.spamhaus.org, b.barracudacentral.org, all.spamrats.com

**Comment by Yerrun** [comment]
Also this one

Spam log: Disallowed words (komputer) are used.

Komputer is computer in Indonesian.

**Comment by Yerrun** [comment]
I need to disable the plugin on one website because the risk of emails ending up in the spam folder is too big. I cannot get the attachments that came with the form in Flamingo (or maybe I missed it?).

**Comment by erikyo** [comment]
> dsnbl: dnsbl-2.uceprotect.net, dnsbl-3.uceprotect.net, zen.spamhaus.org, b.barracudacentral.org, all.spamrats.com

try to disable some of this (or eventually all of them). this because recently and in some countries dnsbl has become unreliable. 
if you want to stick on dsnbl i can suggest to use only [dnsbl-3.uceprotect.net](https://www.uceprotect.net/en/index.php?m=3&s=5), zen.spamhaus.org, b.barracudacentral.org as servers and assign to them a low spam score for detection. they works but aren't 100% safe

**Comment by Yerrun** [comment]
Okay, Erik. I will try that first on some smaller business sites. Thank you

**Comment by Yerrun** [comment]
I can confirm that all works well now after disabling all of the DNS blocklist servers. Later, I will try them one by one to see which one causes the problem.

**Comment by erikyo** [comment]
I'm finishing the upgrade to 0.6.1 just now, and you are just in time to confirm this... So i this that I am going to change also the settings for dnsbl a bit, with fewer servers and less evaluation as they are not as reliable as they used to be (anyhow they aren't to be thrown away though). thanks!
